version: 2
jobs:
  build:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: make test
